import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import '../models/user_profile.dart';
import '../theme/app_theme.dart';
import 'profile_setup_screen.dart';

class OnboardingScreen extends StatefulWidget {
  const OnboardingScreen({super.key});

  @override
  State<OnboardingScreen> createState() => _OnboardingScreenState();
}

class _OnboardingScreenState extends State<OnboardingScreen>
    with TickerProviderStateMixin {
  final PageController _pageController = PageController();
  int _currentPage = 0;

  late AnimationController _floatController;
  late AnimationController _fadeController;
  late Animation<double> _floatAnimation;
  late Animation<double> _fadeAnimation;

  final List<_SlideData> _slides = const [
    _SlideData(
      title: 'AI Powered\nWorkout Coach',
      subtitle: 'Get personalized workout plans generated by Gemini AI based on your fitness goals and level.',
      icon: Icons.auto_awesome_rounded,
      gradient: [Color(0xFF6C63FF), Color(0xFF9C94FF)],
      bubbleIcons: [
        Icons.fitness_center_rounded,
        Icons.auto_awesome_rounded,
        Icons.trending_up_rounded,
        Icons.emoji_events_rounded,
      ],
    ),
    _SlideData(
      title: 'Real-Time\nPosture Analysis',
      subtitle: 'ML-powered pose detection tracks your form and counts reps automatically. No guessing.',
      icon: Icons.videocam_rounded,
      gradient: [Color(0xFF03DAC6), Color(0xFF018786)],
      bubbleIcons: [
        Icons.camera_alt_rounded,
        Icons.accessibility_new_rounded,
        Icons.check_circle_rounded,
        Icons.repeat_rounded,
      ],
    ),
    _SlideData(
      title: 'Track Your\nProgress',
      subtitle: 'Monitor streaks, weekly sessions, total reps and your fitness journey over time.',
      icon: Icons.bar_chart_rounded,
      gradient: [Color(0xFFFF6B6B), Color(0xFFFF8E53)],
      bubbleIcons: [
        Icons.local_fire_department_rounded,
        Icons.calendar_today_rounded,
        Icons.show_chart_rounded,
        Icons.star_rounded,
      ],
    ),
  ];

  @override
  void initState() {
    super.initState();
    SystemChrome.setSystemUIOverlayStyle(const SystemUiOverlayStyle(
      statusBarColor: Colors.transparent,
      statusBarIconBrightness: Brightness.light,
    ));
    _floatController = AnimationController(
      vsync: this,
      duration: const Duration(milliseconds: 2000),
    )..repeat(reverse: true);
    _fadeController = AnimationController(
      vsync: this,
      duration: const Duration(milliseconds: 500),
    )..forward();
    _floatAnimation = Tween<double>(begin: -10, end: 10).animate(
      CurvedAnimation(parent: _floatController, curve: Curves.easeInOut),
    );
    _fadeAnimation = Tween<double>(begin: 0, end: 1).animate(
      CurvedAnimation(parent: _fadeController, curve: Curves.easeIn),
    );
  }

  @override
  void dispose() {
    _pageController.dispose();
    _floatController.dispose();
    _fadeController.dispose();
    super.dispose();
  }

  void _nextPage() {
    if (_currentPage < _slides.length - 1) {
      _fadeController.reset();
      _fadeController.forward();
      _pageController.nextPage(
        duration: const Duration(milliseconds: 500),
        curve: Curves.easeInOut,
      );
    } else {
      _goToProfileSetup();
    }
  }

  void _goToProfileSetup() {
    Navigator.pushReplacement(
      context,
      PageRouteBuilder(
        pageBuilder: (_, __, ___) => const ProfileSetupScreen(),
        transitionsBuilder: (_, animation, __, child) =>
            FadeTransition(opacity: animation, child: child),
        transitionDuration: const Duration(milliseconds: 500),
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    final slide = _slides[_currentPage];
    return Scaffold(
      body: AnimatedContainer(
        duration: const Duration(milliseconds: 500),
        decoration: BoxDecoration(
          gradient: LinearGradient(
            begin: Alignment.topLeft,
            end: Alignment.bottomRight,
            colors: slide.gradient,
          ),
        ),
        child: SafeArea(
          child: Column(children: [
            _buildTopBar(),
            Expanded(
              child: PageView.builder(
                controller: _pageController,
                onPageChanged: (index) {
                  _fadeController.reset();
                  _fadeController.forward();
                  setState(() => _currentPage = index);
                },
                itemCount: _slides.length,
                itemBuilder: (_, index) => _buildSlide(_slides[index]),
              ),
            ),
            _buildBottomBar(slide),
          ]),
        ),
      ),
    );
  }

  Widget _buildTopBar() {
    return Padding(
      padding: const EdgeInsets.symmetric(horizontal: 24, vertical: 16),
      child: Row(
        mainAxisAlignment: MainAxisAlignment.spaceBetween,
        children: [
          Row(
            children: List.generate(_slides.length, (index) {
              final isActive = index == _currentPage;
              return AnimatedContainer(
                duration: const Duration(milliseconds: 300),
                margin: const EdgeInsets.only(right: 6),
                width: isActive ? 24 : 8,
                height: 8,
                decoration: BoxDecoration(
                  color: isActive ? Colors.white : Colors.white.withOpacity(0.4),
                  borderRadius: BorderRadius.circular(4),
                ),
              );
            }),
          ),
          if (_currentPage < _slides.length - 1)
            GestureDetector(
              onTap: _goToProfileSetup,
              child: Container(
                padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 8),
                decoration: BoxDecoration(
                  color: Colors.white.withOpacity(0.2),
                  borderRadius: BorderRadius.circular(20),
                ),
                child: const Text('Skip',
                    style: TextStyle(color: Colors.white, fontWeight: FontWeight.w600, fontSize: 13)),
              ),
            )
          else
            const SizedBox(width: 60),
        ],
      ),
    );
  }

  Widget _buildSlide(_SlideData data) {
    return FadeTransition(
      opacity: _fadeAnimation,
      child: Padding(
        padding: const EdgeInsets.symmetric(horizontal: 32),
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            _buildIllustration(data),
            const SizedBox(height: 48),
            Text(data.title,
                textAlign: TextAlign.center,
                style: const TextStyle(
                    fontSize: 32, fontWeight: FontWeight.w900,
                    color: Colors.white, height: 1.2, letterSpacing: -0.5)),
            const SizedBox(height: 16),
            Text(data.subtitle,
                textAlign: TextAlign.center,
                style: TextStyle(
                    fontSize: 15, color: Colors.white.withOpacity(0.85), height: 1.6)),
          ],
        ),
      ),
    );
  }

  Widget _buildIllustration(_SlideData data) {
    return AnimatedBuilder(
      animation: _floatAnimation,
      builder: (_, child) =>
          Transform.translate(offset: Offset(0, _floatAnimation.value), child: child),
      child: SizedBox(
        height: 240, width: 240,
        child: Stack(
          alignment: Alignment.center,
          children: [
            Container(width: 200, height: 200,
                decoration: BoxDecoration(color: Colors.white.withOpacity(0.12), shape: BoxShape.circle)),
            Container(width: 140, height: 140,
                decoration: BoxDecoration(color: Colors.white.withOpacity(0.18), shape: BoxShape.circle)),
            Container(
              width: 90, height: 90,
              decoration: BoxDecoration(
                color: Colors.white.withOpacity(0.95),
                shape: BoxShape.circle,
                boxShadow: [BoxShadow(color: Colors.black.withOpacity(0.15), blurRadius: 20, offset: const Offset(0, 8))],
              ),
              child: Icon(data.icon, size: 44, color: data.gradient[0]),
            ),
            ..._buildBubbles(data),
          ],
        ),
      ),
    );
  }

  List<Widget> _buildBubbles(_SlideData data) {
    const positions = [
      Offset(-100, -55), Offset(100, -55),
      Offset(-100, 55),  Offset(100, 55),
    ];
    return List.generate(data.bubbleIcons.length, (i) {
      return Positioned(
        left: 120 + positions[i].dx,
        top: 120 + positions[i].dy,
        child: TweenAnimationBuilder<double>(
          tween: Tween(begin: 0, end: 1),
          duration: Duration(milliseconds: 400 + (i * 150)),
          curve: Curves.elasticOut,
          builder: (_, value, child) => Transform.scale(scale: value, child: child),
          child: Container(
            width: 42, height: 42,
            decoration: BoxDecoration(
              color: Colors.white, shape: BoxShape.circle,
              boxShadow: [BoxShadow(color: Colors.black.withOpacity(0.12), blurRadius: 8, offset: const Offset(0, 4))],
            ),
            child: Icon(data.bubbleIcons[i], size: 20, color: data.gradient[0]),
          ),
        ),
      );
    });
  }

  Widget _buildBottomBar(_SlideData data) {
    final isLast = _currentPage == _slides.length - 1;
    return Padding(
      padding: const EdgeInsets.fromLTRB(32, 0, 32, 32),
      child: GestureDetector(
        onTap: _nextPage,
        child: Container(
          width: double.infinity,
          padding: const EdgeInsets.symmetric(vertical: 18),
          decoration: BoxDecoration(
            color: Colors.white,
            borderRadius: BorderRadius.circular(20),
            boxShadow: [BoxShadow(color: Colors.black.withOpacity(0.15), blurRadius: 20, offset: const Offset(0, 8))],
          ),
          child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [
            Text(isLast ? 'Set Up My Profile' : 'Next',
                style: TextStyle(fontSize: 17, fontWeight: FontWeight.w800, color: data.gradient[0])),
            const SizedBox(width: 8),
            Icon(isLast ? Icons.person_add_rounded : Icons.arrow_forward_rounded,
                color: data.gradient[0], size: 20),
          ]),
        ),
      ),
    );
  }
}

class _SlideData {
  final String title;
  final String subtitle;
  final List<Color> gradient;
  final IconData icon;
  final List<IconData> bubbleIcons;

  const _SlideData({
    required this.title, required this.subtitle,
    required this.gradient, required this.icon,
    required this.bubbleIcons,
  });
}